config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signup', to: "users#new", via: 'get'

  match '/about', to: "welcome#about", via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/home', to: 'welcome#map', via: 'get'
  match '/add', to: 'welcome#add', via: 'post'
  match '/submit', to: 'welcome#submit', via: 'get'
  match '/clear', to: 'welcome#clear', via: 'post'
  match '/weather', to: 'welcome#weather', via: 'post'
  
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/contacts', to: 'contacts#new', via: 'get'

  resources "contacts", only: [:new, :create]

  root 'welcome#map'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact",
      :to => "k57cag5@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/coordinates.rb
class Coordinates < ActiveRecord::Base
  belongs_to :provinces
  validates :logitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
end

app/models/jam.rb
class Jam < ActiveRecord::Base
  validates :lat, :lng, numericality: true
  validates :reason, presence: true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_one :coordinates
  has_one :weather
  validates :name , presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 20, minimum: 6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/models/weather.rb
class Weather < ActiveRecord::Base
  belongs_to :provinces
  DAY_REG = /Mon|Tue|Wed|Thu|Fri|Sat|Sun/
  validates :day, presence: true, length: { is: 3 }, format: { with: DAY_REG }
  validates :status, presence: true
  validates :max_temperature, numericality: { less_than_or_equal_to: 50 }
  validates :min_temperature, numericality: { greater_than_or_equal_to: -50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      signin(user)
      redirect_to home_path
    else
      flash[:error] = 'Invaild email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
require 'open-uri'

class WelcomeController < ApplicationController

  def about
    render "about"
  end

  def contact
    render "contact"
  end

  def submit
    if signed_in?
      @jam_places = Jam.all
      render "submit"
    else
      redirect_to signin_path
    end
  end

  def add
    new_jam = Jam.create(:lat => params[:jam_lat], :lng => params[:jam_lng],
    :reason => params[:jam_reason], :place => params[:jam_place])
    if !new_jam.valid?
      flash[:error] = "There were some input errors. Please input again."
    else
      flash[:success] = "Added successfully."
    end
    redirect_to :action => 'submit'
  end

  def clear
    params[:jam_checkbox].each do |check|
      target = Jam.find_by_id(check)
      target.destroy
    end
    redirect_to :action => 'submit'
  end

  def map
    if signed_in?
      @jam_places = Jam.all
      render 'map'
    else
      redirect_to signin_path
    end
  end

  def weather
    @city_id =  params[:city_id]
    @xml_url = 'http://api.openweathermap.org/data/2.5/weather?id=' + @city_id
    @weather_xml = open(@xml_url).read
    @data = ActiveSupport::JSON.decode(@weather_xml)
    respond_to do |format|
      format.html { render 'weather', layout: false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  attr_writer :current_user
  def signin(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  # def current_user=(user)
  #   @current_user = user
  # end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper	
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:700&subset=latin,english' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>

<%  provide(:title,"Contact") %>

<div id="contact">  

    <div id="col-1" class="col">
      <div id="z1" class="contact-zone">
        <div style="padding: 10px, 0">
          <div id="email-logo"><%= image_tag "email_logo.png" %></div>
          <h2 id="z1-text">CONTACT</h2>
        </div>
      </div>

      <div id="z2" class="contact-zone" style="padding: 10px;">
        <h5>If you have any ideas or concern about our project, feel free to contact us:</h5>
      </div>

      <div id="z3" class="contact-zone">
        <div id="form" class="contact-form">
          <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
            <%= f.input :name, :required => true %>
            <%= f.input :email, :required => true %>
            <%= f.input :message, :as => :text, :required => true %>
            <div class= "hidden">
              <%= f.input :nickname, :hint => 'Leave this field blank!' %>
            </div>
            <div>
              </br>
              <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>  
    </div>

    <div id="col-2" class="col">
      <div id="z4" class="contact-zone">
        <h1>04-1214.653.275</h1>
        <h3 style="margin-top: 10px">thongnt_57@vnu.edu.vn</h3>
      </div>
      
      <div id="z5" class="contact-zone noborder">
        <div id="map2">
          <div id="map-canvas2" class="nopad" ></div>
          &nbsp;
          <div id="warnings_panel" ></div>
          <script type="text/javascript">  
            initialize2();
          </script>
        </div>  
        <h4><b>K57CA - Information Technology Faculty - Vietnam National University, Hanoi - University of Engineering and Technology</b></h4>
        <h5>Address: 124 Xuan Thuy, Dich Vong Hau, Cau Giay, Hanoi</h5>
      </div>
    </div>
</div>
  

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="#">Hanoi Easy Traffic</a>		
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>  			
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<!-- Search Bar -->
    <div id="gc-googlebar">
      <%= link_to(image_tag("logo.png"),root_url,  id: "gc-logo", class: "reload") %>

      <form class="gc-search form-inline" role="search">
        <div class="form-group custom-searchbox" style="border-radius:0px;">          
          <input id="pac-input" type="text" class="form-control custom-form" placeholder='Search' autocomplete="on" />
        </div>
        <button type="submit" class="btn btn-primary" style="width: 60px;">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </form>
    </div>

<!-- Navigation Bar -->
    <nav class="navbar navbar-inverse custom-navbar" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav custom-nav">
               <li class="float-left">
                    <%= link_to("About us", about_path, class: "reload") %> 
               </li>            
               <li class="float-left">
                    <%= link_to("Contact us", contacts_path, class: "reload") %>
               </li>               
                <% if signed_in? %>                    
                    <li id="fat-menu" class="dropdown float-right">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Account <b class="caret"></b>
                       </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user,class: "reload" %></li>
                        <li><%= link_to "Settings", '#' %></li>
                        <li class="divider"></li>
                        <li>
                          <%= link_to "Sign out", signout_path, method: "delete", class: "reload" %>
                        </li>
                      </ul>
                    </li>
                <% else %>
                    <li class="float-right"><%= link_to "Sign in", signin_path, class: "reload" %></li>
                <% end %>                                     
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>          
</header>

app/views/layouts/_left_slidebar.html.erb
<!-- Sidebar -->
<div id="sidebar" class="col-md-3 panel-group sidebar">
  <div class="panel-group" id="accordion">
    <!-- Title -->
    <div class="panel panel-default option-style">
      <a class="link-to-page" data-toggle="collapse" data-parent="#accordion" href="#feature1">
      <div class="panel-heading find-route">
        <h4 class="panel-title">Find Route </h4>
      </div> </a>
      <!-- Body -->
      <div id="feature1" class="find-route panel-collapse collapse">
        <div class="panel-body">
          <div class="title-details">
            <p>
              Choose vehicle:
            </p>
          </div>
          <div class="vehicle-icon bottom-space-standard">
            <div rel="car" class="vehicle-type car"></div>
            <div rel="bus" class="vehicle-type bus"></div>
            <div rel="bike1" class="vehicle-type bike"></div>
            <div rel="walk" class="vehicle-type walk"></div>
          </div>
          <div class="route-input">
            <div class="input-box bottom-space-standard" text-align="center">
              <input class="input-text form-control" id="start-place" type="text" placeholder="Enter start place">
            </div>
            <div class="input-box bottom-space-standard" text-align="center">
              <input class="input-text form-control" id="end-place" type="text" placeholder="Enter second place">
            </div>
            <div class="submit-box bottom-space-standard">
              <button type="submit" class="submit-btn btn btn-primary find-btn" style="width: 60px;">
                <span class="glyphicon glyphicon glyphicon-hand-right"></span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-default option-style">
      <a data-toggle="collapse" data-parent="#accordion" href="#feature2">
      <div class="panel-heading traffic-information">
        <h4 class="panel-title"> Traffic Information </h4>
      </div> </a>

      <div id="feature2" class="panel-collapse collapse">
        <div class="panel-body">
          <button id="traffic-button" type="submit" class="submit-btn btn btn-primary submit-info" style="width: 60px;">
            Show
          </button>
          <a href="/submit" class="submit-btn btn btn-primary">Submit</a>
        </div>
      </div>
    </div>

    <div class="panel panel-default option-style">
      <a data-toggle="collapse" data-parent="#accordion" href="#feature3">
      <div class="panel-heading weather">
        <h4 class="panel-title"> Weather </h4>
      </div> </a>
      <div id="feature3" class="panel-collapse collapse">
        <div class="panel-body">
          <select class="weather-select-box form-control" >
            <option value="1581130">Ha Noi</option>
            <option value="1562798">Vinh</option>
            <option value="1591449">Bac Ninh</option>
            <option value="1591527">Bac Giang</option>
            <option value="1581326">Hai Duong</option>
            <option value="1562548">Vinh Yen</option>
          </select>
          <div class="current-weather"></div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_map_canvas.html.erb
<div id="map" class="col-md-9 nopad">
  <div id="map-canvas" class="nopad"></div>
  <div id="over-map">
    <a id="toggleSidebar" class="toggles"><i class="glyphicon glyphicon-chevron-left"></i></a>
  </div>
</div>
<div id="warnings_panel" style="width:100%;height:10%;text-align:center"></div>
<script type="text/javascript">
	initializeMap('map-canvas', 'pac-input');
	$('#map-canvas').width($('#map-canvas').parent().width());
	$('#map-canvas').height($(window).height() - 120); 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hanoi Easy Traffic" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hanoi Easy Traffic" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDF8iBU12PVuIu03Xfp55ebFVehhNj_YAY&sensor=false&libraries=places"></script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container custom-container">
      <%= yield %>
      <div class="weather-container"></div>
    </div>
    <script type="text/javascript">
		var hgt = $('.container-fluid').height();
    </script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title,"Sign Up") %>
<h1 algin="center">Sign Up</h1>
<div class="authentication-div span6 offset3" >	
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name, :class => 'form-control sign-in-out-form' %>

		<%= f.label :email %>		
		<%= f.text_field :email, :class => 'form-control sign-in-out-form' %>			

		<%= f.label :password %>
		<%= f.password_field :password, :class => 'form-control sign-in-out-form' %>

		<%= f.label :password_confirmation %>			
		<%= f.password_field :password_confirmation, :class => 'form-control sign-in-out-form' %>		

		<%= f.submit "Create my account", class: "btn btn-large btn-primary btn-sign-in-out" %>
		<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>

app/views/welcome/about.html.erb
<%  provide(:title,"About Us") %>
<div class="about-us">  

  <div id="col-about" class="col">
      <div id="z1" class="about-zone">
        <div style="padding: 10px, 0">
          <<h1 >About Us</h1>
        </div>
      </div>

      <div id="z2" class="about-zone" style="padding: 10px;">
        <ul>
          <li> Dự án : Hanoi Easy Traffic</li>
          <li> Nhóm: 5 - K57CA - Đại học Công Nghệ - ĐHQG</li>
          <li> Languages and Frameworks: Ruby/Rails, HTML/CSS/Bootstrap, JavaScript/Jquery/Dom</li>
        </ul>
      </div>

      <div id="z3" class="about-zone">
        </br>
        <ul>
            <li> Xem bản đồ giao thông của Hà Nội</li></br>
            <li> Tìm đường đi, các tuyến xe buýt</li></br>
            <li> Theo dõi tình hình thời tiếc và tình hình ác tắc giao thông</li></br>
            <li> Cung cấp và chia sẻ thông tin giao thông </li></br>
            <li> Các tính năng khác đang được lên kế hoạch...</li>
        </ul>
      </div>  
    </div>

  
    
        

app/views/welcome/contact.html.erb
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:700&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>

<%  provide(:title,"Contact") %>

<div id="contact">  

    <div id="col-1" class="col">
      <div id="z1" class="contact-zone">
        <div style="padding: 10px, 0">
          <div id="email-logo"><%= image_tag "email_logo.png" %></div>
          <h2 id="z1-text">LIÊN HỆ</h2>  
        </div>
      </div>

      <div id="z2" class="contact-zone" style="padding: 10px;">
        <h5>Nếu bạn có bất cứ góp ý gì cho Project của nhóm, hãy gửi tin nhắn theo mẫu ở dưới, chúng tôi sẽ trả lời nhanh nhất có thể:</h5>
      </div>

      <div id="z3" class="contact-zone">
        <form class="contact-form" enctype="text/plain">
          <div>
            <label class="contact-label" for="name">Name:</label></br>
            <input type="text" id="name" name="user_name" />
          </div>
          <div>
            <label class="contact-label" for="mail">E-mail:</label></br>
              <input type="email" id="mail" name="user_email" />
          </div>
          <div>
            <label class="contact-label" for="name">Chủ đề:</label></br>
            <input type="text" id="subject" name="user_subject" />
          </div>
          <div>
            <label class="contact-label" for="msg">Nội dung:</label></br>
            <textarea id="msg" name="user_message" placeholder="Bạn vui lòng điền nội dung liên hệ và góp ý bên dưới:"></textarea>
          </div>
            <div class="button">
              <button class="contact-button" type="submit">Gửi</button>
          </div>
        </form>
      </div>  
    </div>

    <div id="col-2" class="col">
      <div id="z4" class="contact-zone">
        <h1>04-1214.653.275</h1>
        <h3 style="margin-top: 10px">thongnt_57@vnu.edu.vn</h3>
      </div>
      
      <div id="z5" class="contact-zone noborder">
        <div id="map2">
          <div id="map-canvas2" class="nopad" ></div>
          &nbsp;
          <div id="warnings_panel" ></div>
          <script type="text/javascript">  
            initialize2();
          </script>
        </div>  
        <h4><b>Trụ sở: K57CA - Ngành: Công Nghệ Thông Tin. Đại học Công Nghệ - Đại học Quốc Gia Hà Nội</b></h4>
        <h5>Địa chỉ: 24 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội</h5>      
      </div>
    </div>
  

app/views/welcome/index.html.erb
<script type='text/javascript'>
    $(document).ready(function() {
        $('#mapCanvas').width($('#mapCanvas').parent().width());
        $('#mapCanvas').height($(window).height() - 120);
        $('#sidebar').height($('#mapCanvas').height() - 20);
        $(".panel-heading")
                .mouseover(function() {
                    $(this).addClass('mouseover');
                })
                .mouseout(function() {
                    $(this).removeClass('mouseover');
                });

        $(".panel-heading").click(function(e) {
            e.preventDefault(); //prevent the link from actually navigating somewhere
            $(this).toggleClass("clicked");
            $(".panel-heading").not(this).removeClass("clicked"); //remove the clicked class from all other elements
        });
    });

    $(window).load(function(){
        $.asm = {};
        $.asm.panels = 2;
        
        function sidebar(panels) {
            $.asm.panels = panels;
            if (panels === 1) {
                $('#sidebar').hide();
                $('#map').removeClass('col-md-9')
                $('#mapCanvas').width($('#mapCanvas').parent().width());
                $('#mapCanvas').height($(window).height() - 120);
            } else if (panels === 2) {
                $('#map').addClass('col-md-9')
                $('#sidebar').show();
                $('#mapCanvas').width($('#mapCanvas').parent().width());
                $('#sidebar').height($('#mapCanvas').height() - 20);
                return google.maps.event.trigger($.asm.theMap, 'resize');
            }
        };

        $('#toggleSidebar').click(function() {
            if ($.asm.panels === 1) {
                $('#toggleSidebar i').addClass('glyphicon-chevron-left');
                $('#toggleSidebar i').removeClass('glyphicon-chevron-right');
                return sidebar(2);
            } else {
                $('#toggleSidebar i').removeClass('glyphicon-chevron-left');
                $('#toggleSidebar i').addClass('glyphicon-chevron-right');
                return sidebar(1);
            }
        });

        $(function() {
            $.asm.theMap = new google.maps.Map(document.getElementById('mapCanvas'));
        });
    });
</script>

<div class="container-fluid">
  <div class="row">
    <!-- Sidebar -->
    <div id="sidebar" class="col-md-3 panel-group sidebar">
      <div class="panel-group" id="accordion">
        <!-- Title -->
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature1">
            <div class="panel-heading">
              <h4 class="panel-title">
                Feature 1
              </h4>
            </div>
          </a>
          <!-- Body -->
          <div id="feature1" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature2">
            <div class="panel-heading">
            <h4 class="panel-title">
                Feature 2
            </h4>
            </div>
          </a>
          <div id="feature2" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature3">
            <div class="panel-heading">
              <h4 class="panel-title">
                Feature 3
              </h4>
            </div>
          </a>
          <div id="feature3" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature4">
            <div class="panel-heading">
              <h4 class="panel-title">
                Feature 4
              </h4>
            </div>
          </a>
          <div id="feature4" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature5">
            <div class="panel-heading">
              <h4 class="panel-title">
                Feature 5
              </h4>
            </div>
          </a>
          <div id="feature5" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
        <div class="panel panel-default option-style">
          <a data-toggle="collapse" data-parent="#accordion" href="#feature6">
            <div class="panel-heading">
              <h4 class="panel-title">
                Feature 6
              </h4>
            </div>
          </a>
          <div id="feature6" class="panel-collapse collapse">
            <div class="panel-body">
              In developing!
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="map" class="col-md-9 nopad">
      <iframe id="mapCanvas" src="../welcome/map"></iframe>
      <div id="over-map">
        <a id="toggleSidebar" class="toggles"><i class="glyphicon glyphicon-chevron-left"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/welcome/map.html.erb
<%= render 'layouts/left_slidebar' %>
<%= render 'layouts/map_canvas' %>
<%= javascript_tag do %>
    <% @jam_places.each do |jam_place| %>
        jamLat.push(<%= jam_place.lat %>);
        jamLgn.push(<%= jam_place.lng %>);
        jamReason.push("<%= jam_place.reason %>");
    <% end %>
<% end %>

app/views/welcome/weather.html.erb
<div class="span4 current-weather-content">
<% img_url = "weather/"+@data['weather'][0]['icon']+".png"  %>
<h3 class="text-in-weather"><%= image_tag(img_url) %> <%= @data['name']  %> </h3>

<h2 class="text-in-weather"><%= (@data['main']['temp']-272.5).round(2) %>°C</h2>
 <%= @data['weather'][0]['description'] %>
<p></p><div id="date_m"><%= Time.now %></div><p></p>

<table class="table table-striped table-bordered table-condensed">
<tbody>

<tr><td><%= @data['weather'][0]['main'] %></td><td><%= @data['clouds']['all'] %></td></tr>
<tr><td>Pressure</td><td><%= @data['main']['pressure'] %> hpa</td></tr>
<tr><td>Pressure<br> (sea level)</td><td><%= @data['main']['sea_level'] %> hpa</td></tr>	
<tr><td>Humidity</td><td><%= @data['main']['humidity'] %> %</td></tr>
<tr><td>Sunrise</td><td id="sunrise"><%= @data['sys']['sunrise'] %></td></tr>
<tr><td>Sunset</td><td id="sunset"><%= @data['sys']['sunset'] %></td></tr>
</tbody>
</table>
</div>

app/views/welcome/weather.js.erb
alert("<%= @temp %>");